### ISSUE TITLE
GroupBy in IQueryable

### ISSUE THREAD

**Issue by KAJOOSH** [NonFactors/AspNetCore.Grid#278]
How is the "GroupBy" command used in Grid?

**Comment by Muchiachio** [comment]
You can use group by in the query, but the grid doesn't do any visual grouping.

**Comment by KAJOOSH** [comment]
My code:
I want the sum of time to be displayed by date
```
            var _model = _context.TicketAction
                .Include(x=> x.ActionUser)
                .ThenInclude(x=> x.Person).GroupBy(X=> X.ActionDate);

@model IQueryable<DataModel.Model.EntityTicket.TicketAction>
@(Html
    .Grid(Model)
    .Build(columns =>
    {

        columns.Add(model => model.ID).Hidden();
        columns.Add(model => model.ActionUser.Person.FullName2).Titled(GlobalizationModel.DisplayName.Tracking).Css("align-middle mw-40");
        columns.Add(model => model.DIFFActionTime).Titled(GlobalizationModel.DisplayName.Tracking).Css("align-middle mw-40");
        columns.Add(model => model.ActionDate).Titled(GlobalizationModel.DisplayName.Tracking).Css("align-middle mw-40");




    })
    .Empty(GlobalizationModel.DisplayName.NoDataFound)
    .Id("my-ajax-grid")
    .Pageable(pager =>
    {
        pager.PageSizes = new Dictionary<Int32, String> { { 0, GlobalizationModel.DisplayName.All }, { 5, "5" }, { 10, "10" } };
        pager.ShowPageSizes = true;
        pager.PagesToDisplay = 3;
        pager.RowsPerPage = 5;
    })
    .Filterable()
    .Sortable()
    .Css("table table-responsive TaskManagement")
)
```
error:
```
System.InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[System.Linq.IGrouping`2[System.DateTime,DataModel.Model.EntityTicket.TicketAction]]', but this ViewDataDictionary instance requires a model item of type 'System.Linq.IQueryable`1[DataModel.Model.EntityTicket.TicketAction]'.
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(Object value)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, Object model, Type declaredModelType)
   at lambda_method(Closure , ViewDataDictionary )
   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.Activate(Object page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.ExecuteAsync(ActionContext context, PartialViewResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

**Comment by Muchiachio** [comment]
Stack trace is not in the grid :)

**Comment by KAJOOSH** [comment]
I'm very sorry
But I didn't understand, please help me :)

**Comment by KAJOOSH** [comment]
I found the problem, but something new was found
I change the code from` '@model IQueryable<DataModel.Model.EntityTicket.TicketAction>'` to `'IQueryable<IGrouping<Object, DataModel.Model.EntityTicket.TicketAction>>'`
The nucleus considers all the columns in which "GROUP BY" is used to find the number of rows
Error SQL:
`Column '.....' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
`
:((

**Comment by KAJOOSH** [comment]
If the core is correct, please provide a sample of the column sum code along with GROUP BY
